---
layout: cv
title: Angela's CV
---
# Angela Chen
Physicist, Mathematician, Cambridge professor.

<div id="webaddress">
<a href="https://angelabyui.github.io/AngelaResume/">https://angelabyui.github.io/AngelaResume/</a>
| <a href="https://www.linkedin.com/in/angelapc-chen/">My LinkedIn page</a>
</div>


## Currently

Working for the Education System in Church of Jesus Christ of Latter Day Saint

### Specialized in

Java | Python | HTML | CSS | JavaScript | Node.JS | React


### Research interests

Meta, Google, Amazon, Microsoft


## Education

`2022-2024`
__Ensign College__

`2025 Sep - now`
__BYU-Idaho__




## Occupation

`Mar 2025 - Jun 2025`
__Family Search | Technical Intern__, Remote, USA

- Developed a Python script using BeautifulSoup to extract over 13,000 rows and 156,000 cells of structured data from 
external websites. Replaced a repetitive manual copy-paste process, estimated at 120+ hours of human effort, with a 
single-click automation, significantly improving speed, accuracy, and scalability. 
- Built a reusable Python CLI tool to inspect, clean, and validate CSV datasets across multiple files. 
- Used pandas to implement functionality such as fixing encodin

`Apr 2024 -  Jun 2025`
__Murdock InfoTech | Web Developer Intern__, Remote, USA

- Developed an IVR system using Twilio's Voice API, customers can navigate menus through voice or keypad inputs 
- Utilized Node.js to log call data, which was later processed for performance analysis and improving customer interactions 
- Authored YAML configuration files and Dockerized the app


<!-- ### Footer

Last updated: Dec 2025 -->